# Generated by Django 3.0.5 on 2022-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('branch', models.CharField(choices=[('ME', 'Mechanical'), ('CS', 'Computer'), ('EXTC', 'Electronic'), ('CE', 'Chemical'), ('IT', 'Information Technology'), ('BSc IT', 'BSc IT'), ('BSc CS', 'BSc CS'), ('Bcom', 'Bcom'), ('BArch', 'BAech'), ('BSc', 'BSc')], max_length=6)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
