# Generated by Django 3.0.5 on 2022-06-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagementsystem', '0003_auto_20220621_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='students',
        ),
    ]
