# Generated by Django 3.0.5 on 2022-06-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagementsystem', '0007_auto_20220621_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='issuedbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('student_id', models.CharField(max_length=50)),
                ('student_phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
